// 定义所有的动作类型
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export type FETCH_DATA_REQUEST = typeof FETCH_DATA_REQUEST;
export type FETCH_DATA_SUCCESS = typeof FETCH_DATA_SUCCESS;
export type FETCH_DATA_FAILURE = typeof FETCH_DATA_FAILURE;
//  请求接口的动作 有三种状态， request success fail

export const DO_CHANGE_NUMBER = 'DO_CHANGE_NUMBER';
export type DO_CHANGE_NUMBER = typeof DO_CHANGE_NUMBER;
//  同步操作，只需要一种状态

export const DO_CHANGE_NAME = 'DO_CHANGE_NAME';
export type DO_CHANGE_NAME = typeof DO_CHANGE_NAME;

export const DO_CHANGE_HOME_TAB = 'DO_CHANGE_HOME_TAB';
export type DO_CHANGE_HOME_TAB = typeof DO_CHANGE_HOME_TAB;

export const FETCH_BANNER_REQUEST = 'FETCH_BANNER_REQUEST';
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS';
export const FETCH_BANNER_FAILURE = 'FETCH_BANNER_FAILURE';
export type FETCH_BANNER_REQUEST = typeof FETCH_BANNER_REQUEST;
export type FETCH_BANNER_SUCCESS = typeof FETCH_BANNER_SUCCESS;
export type FETCH_BANNER_FAILURE = typeof FETCH_BANNER_FAILURE;

export const FETCH_RECOMMEND_SONG_REQUEST = 'FETCH_RECOMMEND_SONG_REQUEST';
export const FETCH_RECOMMEND_SONG_SUCCESS = 'FETCH_RECOMMEND_SONG_SUCCESS';
export const FETCH_RECOMMEND_SONG_FAILURE = 'FETCH_RECOMMEND_SONG_FAILURE';
export type FETCH_RECOMMEND_SONG_REQUEST = typeof FETCH_RECOMMEND_SONG_REQUEST;
export type FETCH_RECOMMEND_SONG_SUCCESS = typeof FETCH_RECOMMEND_SONG_SUCCESS;
export type FETCH_RECOMMEND_SONG_FAILURE = typeof FETCH_RECOMMEND_SONG_FAILURE;


export const FETCH_NEW_SONG_REQUEST = 'FETCH_NEW_SONG_REQUEST';
export const FETCH_NEW_SONG_SUCCESS = 'FETCH_NEW_SONG_SUCCESS';
export const FETCH_NEW_SONG_FAILURE = 'FETCH_NEW_SONG_FAILURE';
export type FETCH_NEW_SONG_REQUEST = typeof FETCH_NEW_SONG_REQUEST;
export type FETCH_NEW_SONG_SUCCESS = typeof FETCH_NEW_SONG_SUCCESS;
export type FETCH_NEW_SONG_FAILURE = typeof FETCH_NEW_SONG_FAILURE;

export const DO_LOGIN_VISIABLE = 'DO_LOGIN_VISIABLE';
export type DO_LOGIN_VISIABLE = typeof DO_LOGIN_VISIABLE;

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';
export type FETCH_LOGIN_REQUEST = typeof FETCH_LOGIN_REQUEST;
export type FETCH_LOGIN_SUCCESS = typeof FETCH_LOGIN_SUCCESS;
export type FETCH_LOGIN_FAILURE = typeof FETCH_LOGIN_FAILURE;


export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILURE = 'FETCH_PLAYLIST_FAILURE';
export type FETCH_PLAYLIST_REQUEST = typeof FETCH_PLAYLIST_REQUEST;
export type FETCH_PLAYLIST_SUCCESS = typeof FETCH_PLAYLIST_SUCCESS;
export type FETCH_PLAYLIST_FAILURE = typeof FETCH_PLAYLIST_FAILURE;


export const FETCH_SONGURL_REQUEST = 'FETCH_SONGURL_REQUEST';
export const FETCH_SONGURL_SUCCESS = 'FETCH_SONGURL_SUCCESS';
export const FETCH_SONGURL_FAILURE = 'FETCH_SONGURL_FAILURE';
export type FETCH_SONGURL_REQUEST = typeof FETCH_SONGURL_REQUEST;
export type FETCH_SONGURL_SUCCESS = typeof FETCH_SONGURL_SUCCESS;
export type FETCH_SONGURL_FAILURE = typeof FETCH_SONGURL_FAILURE;


export const FETCH_PLAY_STATUS = 'FETCH_PLAY_STATUS';
export type FETCH_PLAY_STATUS = typeof FETCH_PLAY_STATUS;

export const FETCH_CURRENT_SONG = 'FETCH_CURRENT_SONG';
export type FETCH_CURRENT_SONG = typeof FETCH_CURRENT_SONG;

export const FETCH_SONG_URL = 'FETCH_SONG_URL';
export type FETCH_SONG_URL = typeof FETCH_SONG_URL;

export const FETCH_CURRENT_DATA = 'FETCH_CURRENT_DATA';
export type FETCH_CURRENT_DATA = typeof FETCH_CURRENT_DATA;

export const FETCH_PROGRESS = 'FETCH_PROGRESS';
export type FETCH_PROGRESS = typeof FETCH_PROGRESS;

export const FETCH_LYRIC_REQUEST = 'FETCH_LYRIC_REQUEST';
export const FETCH_LYRIC_SUCCESS = 'FETCH_LYRIC_SUCCESS';
export const FETCH_LYRIC_FAILURE = 'FETCH_LYRIC_FAILURE';
export type FETCH_LYRIC_REQUEST = typeof FETCH_LYRIC_REQUEST;
export type FETCH_LYRIC_SUCCESS = typeof FETCH_LYRIC_SUCCESS;
export type FETCH_LYRIC_FAILURE = typeof FETCH_LYRIC_FAILURE;
